import type { Metadata } from 'next';
import '@repo/ui/styles.css';
import '@/assets/styles/globals.css';
import PublicHeader from '@/components/global/PublicHeader';
import Providers from '@/components/providers';
import Container from '@/components/layout/Container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PublicHeader />
      <Container tag="main" className="py-6">
        {children}
      </Container>
    </>
  );
}
