import type { Metadata } from 'next';
import '@repo/ui/styles.css';
import '@/assets/styles/globals.css';
import Header from '@/components/global/Header';
import Providers from '@/components/providers';
import Container from '@/components/layout/Container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <Container tag='main' className='py-6'>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
