services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    env_file:
      - .env
    ports:
      - 1027:1025
      - 8027:8025
    volumes:
      - ../../docker-data/mailhog:/maildir
